# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [3]:
import numpy as np

In [4]:
a = np.zeros(100)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Создать вектор размера 100, заполненный единицами

In [5]:
a = np.ones(100)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [13]:
a = np.array([3 for i in range(100)])
a


array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

#### 5. Поменять 2 строки в матрице

In [52]:
def swap(a, b) :
    return b, a

a = np.diag(np.arange(5) + 1)
print(a)
a[2], a[3] = swap(a[2], a[3])

print('\nпачиму ни роботает\n{}'.format(a))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

пачиму ни роботает
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 0 4 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 6. Создать вектор со значениями от 10 до 100

In [26]:
#a = np.array([np.random.rand(10, 100) for i in range(100)])
a = np.random.rand(10)
a

array([0.66366826, 0.73085494, 0.94181509, 0.90510378, 0.13228438,
       0.44859704, 0.00370342, 0.06679975, 0.5624718 , 0.09637137])

#### 7. Развернуть вектор (первый становится последним)

In [40]:
a = np.arange(10)
print(a)
a[::1] = a[::-1]
print(a)

[0 1 2 3 4 5 6 7 8 9]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

#### 10. Создать 3x3 единичную матрицу

#### 11. Создать массив 3x3x3 со случайными значениями

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

#### 14. Создать матрицу с 0 внутри, и 1 на границах

#### 15. Выяснить результат следующих выражений

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [16]:
a = np.array([0, 1])
a = np.tile(a, (8, 4))
#b = np.array(a)
a


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

#### 24. Есть генератор, сделать с его помощью массив

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

#### 26. Отсортировать вектор

#### 27. Проверить, одинаковы ли 2 numpy массива

#### 28. Сделать массив неизменяемым

#### 29. Найти n наибольших значений в массиве

#### 30. Заменить максимальный элемент на ноль

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

#### 34. Напечатать все значения в массиве

#### 35. Найти ближайшее к заданному значению число в заданном массиве

#### 36. Преобразовать массив из float в int

#### 37. Каков эквивалент функции enumerate для numpy массивов?

#### 38. Случайно расположить p элементов в 2D массив

#### 39. Отнять среднее из каждой строки в матрице

#### 40. Отсортировать матрицу по n-ому столбцу

#### 41. Определить, есть ли в 2D массиве нулевые столбцы

#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

Оригинал: <https://github.com/rougier/numpy-100>