# Домашнее задание



Всего у вас 2 домашних задания:

### 1) Обучите модель линейной регрессии на примере (6 баллов)
(в этом файле)

### 2) Решите доп. задачи в файле с занятием (6 баллов)
(в файле 3_LinearRegression.ipynb)

Вы получите по баллу за задачу.

# Линейная регрессия (суммарно 5 баллов)
В этом задании надо научиться предсказывать цены в датасете с квартирами Бостона.

### (0 баллов) Считываем данные

In [18]:
import scipy
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [19]:
from sklearn.datasets import load_boston

dataset = load_boston()
dataset.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

Каждая квартира имеет 13 признаков:

In [20]:
X = dataset['data']
#X[:10]

In [21]:
dataset['feature_names']

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [22]:
#print(dataset['DESCR'])

Хочется научиться предсказывать функцию цены квартиры. Предположительно, она зависит как-то от этих признаков.

In [23]:
y = dataset['target']
y[:10]

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9])

### (1 балл) Разделите данные на тренировочную и тестовую части.

Тестовая часть должна составлять 10% выборки.


In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

### (1 балл) Обучение и применение модели
Обучите модель линейной регрессии на тренировочной части и предскажите результаты на тестовой части.


In [34]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [35]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [36]:
y_pred = model.predict(X_test)
y_pred

array([17.60531188, 23.8080192 , 33.7627468 , 17.59787445,  7.11219694,
       27.58370582, 24.12471303, 14.69031246, 37.12342384, 33.86040323,
       29.05502701, 22.21706673, 21.96721066, 38.61783629, 20.29119125,
       41.95006319, 19.04657372, 33.8573813 , 22.48587171, 17.53280854,
       34.11654027, 28.84243444, 32.57567681, 15.6674074 , 17.62070739,
       38.52081754, 37.46018829, 18.3217115 , 30.63899371, 25.40286675,
       30.63198878, 30.90903087, 16.71055573, 27.3182278 ,  9.96727858,
       32.63526062,  8.78233182, 16.88163476, 24.89971561, 24.71280097,
       19.12601477, 12.80105995, 22.94959031, 18.42253285, 12.91676198,
       27.23341765, 21.07998471, 20.36997239, 18.05423469, 18.49496667,
       16.63591077])

In [37]:
y_test

array([13. , 23. , 37.9, 15.1,  5. , 23.9, 23.4, 11. , 48.3, 26.7, 23.6,
       21.4, 19.3, 21.9, 21.5, 50. , 10.9, 32. , 20. , 17.8, 35.4, 22.9,
       41.3, 15.6, 19.6, 45.4, 37.6, 18.9, 23.5, 23.1, 25.1, 29.4, 13.8,
       22. ,  7.2, 30.3,  7.2, 19.4, 27.5, 30.1, 18.5, 13.1, 19.8, 13.9,
       13.5, 22.6, 24.5, 22.9, 14.9, 15.4, 19.4])

### (2 балл) Валидация результата

Напишите свою функцию MSE и посчитайте своей результат на тестовой части.

In [38]:
def MSE(y_real, y_pred):
    return np.sum((y_real - y_pred)**2) / len(y_real)

In [39]:
MSE(y_test, y_pred)

22.72903751690998

Насколько хорошо вы предсказали GDP? Сравните с наивным алгоритмом (предсказать средний GDP на тренировочной части вне зависимости от признаков).

In [40]:
y_pred = np.mean(y_test)
MSE(y_test, y_pred)

98.24698961937716

In [32]:
# MSE наивного алгоритма более чем в 4 раза больше MSE нашей обученной модели

### (2 балла) Улучшите результат.

Возможно, происходит переобучение, попробуйте применить регуляризацию, чтобы улучшить результат (то есть используйте Ridge вместо LinearRegression).

Нарисуйте график зависимости MSE от коэффициента регуляризации.

In [71]:
from sklearn.linear_model import Ridge
model2 = Ridge(alpha=100)

In [72]:
model2.fit(X_train, y_train)

Ridge(alpha=100, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [73]:
y_pred = model2.predict(X_test)
y_pred

array([17.6771155 , 22.47859514, 33.19815473, 18.79435029,  6.60702086,
       27.90250595, 23.26049332, 14.20407026, 34.78547397, 29.94999086,
       28.87500503, 21.59621043, 22.70889765, 33.89434968, 24.53975008,
       36.65542076, 17.60176364, 32.29917183, 23.13934172, 17.74385379,
       33.69823955, 28.10199571, 32.16278873, 16.54183048, 23.24069259,
       36.65614042, 35.42789231, 19.13617383, 31.16802481, 26.70803611,
       27.7404038 , 31.06663811, 16.38791276, 27.0701373 ,  8.08874603,
       31.47293238,  8.55794091, 17.34461192, 24.08392162, 27.77094717,
       21.28001891, 18.45305744, 22.07487488, 16.4194763 , 14.55149131,
       27.03235262, 21.43212144, 21.8346469 , 18.89925373, 18.87700953,
       21.4332268 ])

In [74]:
y_test

array([13. , 23. , 37.9, 15.1,  5. , 23.9, 23.4, 11. , 48.3, 26.7, 23.6,
       21.4, 19.3, 21.9, 21.5, 50. , 10.9, 32. , 20. , 17.8, 35.4, 22.9,
       41.3, 15.6, 19.6, 45.4, 37.6, 18.9, 23.5, 23.1, 25.1, 29.4, 13.8,
       22. ,  7.2, 30.3,  7.2, 19.4, 27.5, 30.1, 18.5, 13.1, 19.8, 13.9,
       13.5, 22.6, 24.5, 22.9, 14.9, 15.4, 19.4])

In [75]:
MSE(y_test, y_pred)

22.844331057107674

In [76]:
y_pred = np.mean(y_test)
MSE(y_test, y_pred)

98.24698961937716

Помогает ли регуляризация? Какой коэффициент регуляризации надо выбрать, чтобы ошибка была минимальной? Чему при этом равна ошибка?